### ISSUE TITLE
Need informations

### ISSUE THREAD

**Issue by wastez** [ksjh/silabs-firmware-builder#3]
1st i've to say thanks for your work in this project, it's really great that somebody is working on it. 

I want also to experiment with this firmware on a dongle-e.
right now I’m using fw version 7.1.1 in combination with zigbee2mqtt. 
Does anybody know if the zigbee devices will still work which are still added to zigbee2mqtt if I’m going to flash this fw?

Would be great if someone can answer this.

**Comment by ksjh** [comment]
I have not tried this, but according to the [zigbee2mqtt FAQ](https://www.zigbee2mqtt.io/guide/faq/#what-does-and-does-not-require-repairing-of-all-devices), you should not need to repair your devices, the IEEE address would stay the same. But: no guarantees for this.

**Comment by ksjh** [comment]
And more info can also be found in the zigbee2mqtt FAQ about [migrating between different adapters](https://www.zigbee2mqtt.io/guide/faq/#how-do-i-migrate-from-one-adapter-to-another).
